version: '3.9'

services:
  app:
    build: .
    container_name: canciones
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongo
    env_file: # Carga las variables desde el .env
      - .env

  mongo:
    image: mongo:6
    container_name: mongo_canciones
    ports:
      - "${DB_PORT}:27017"
    env_file: 
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
